// Code generated by ent, DO NOT EDIT.

package ent

import (
	"baseProject/ent/predicate"
	"baseProject/ent/price"
	"baseProject/ent/product"
	"baseProject/ent/store"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PriceUpdate is the builder for updating Price entities.
type PriceUpdate struct {
	config
	hooks    []Hook
	mutation *PriceMutation
}

// Where appends a list predicates to the PriceUpdate builder.
func (pu *PriceUpdate) Where(ps ...predicate.Price) *PriceUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetProductID sets the "product_id" field.
func (pu *PriceUpdate) SetProductID(i int) *PriceUpdate {
	pu.mutation.SetProductID(i)
	return pu
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (pu *PriceUpdate) SetNillableProductID(i *int) *PriceUpdate {
	if i != nil {
		pu.SetProductID(*i)
	}
	return pu
}

// SetStoreID sets the "store_id" field.
func (pu *PriceUpdate) SetStoreID(i int) *PriceUpdate {
	pu.mutation.SetStoreID(i)
	return pu
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (pu *PriceUpdate) SetNillableStoreID(i *int) *PriceUpdate {
	if i != nil {
		pu.SetStoreID(*i)
	}
	return pu
}

// SetPrice sets the "price" field.
func (pu *PriceUpdate) SetPrice(f float64) *PriceUpdate {
	pu.mutation.ResetPrice()
	pu.mutation.SetPrice(f)
	return pu
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (pu *PriceUpdate) SetNillablePrice(f *float64) *PriceUpdate {
	if f != nil {
		pu.SetPrice(*f)
	}
	return pu
}

// AddPrice adds f to the "price" field.
func (pu *PriceUpdate) AddPrice(f float64) *PriceUpdate {
	pu.mutation.AddPrice(f)
	return pu
}

// SetRecordedAt sets the "recorded_at" field.
func (pu *PriceUpdate) SetRecordedAt(t time.Time) *PriceUpdate {
	pu.mutation.SetRecordedAt(t)
	return pu
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (pu *PriceUpdate) SetNillableRecordedAt(t *time.Time) *PriceUpdate {
	if t != nil {
		pu.SetRecordedAt(*t)
	}
	return pu
}

// SetProduct sets the "product" edge to the Product entity.
func (pu *PriceUpdate) SetProduct(p *Product) *PriceUpdate {
	return pu.SetProductID(p.ID)
}

// SetStore sets the "store" edge to the Store entity.
func (pu *PriceUpdate) SetStore(s *Store) *PriceUpdate {
	return pu.SetStoreID(s.ID)
}

// Mutation returns the PriceMutation object of the builder.
func (pu *PriceUpdate) Mutation() *PriceMutation {
	return pu.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (pu *PriceUpdate) ClearProduct() *PriceUpdate {
	pu.mutation.ClearProduct()
	return pu
}

// ClearStore clears the "store" edge to the Store entity.
func (pu *PriceUpdate) ClearStore() *PriceUpdate {
	pu.mutation.ClearStore()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PriceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PriceUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PriceUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PriceUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PriceUpdate) check() error {
	if pu.mutation.ProductCleared() && len(pu.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Price.product"`)
	}
	if pu.mutation.StoreCleared() && len(pu.mutation.StoreIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Price.store"`)
	}
	return nil
}

func (pu *PriceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(price.Table, price.Columns, sqlgraph.NewFieldSpec(price.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Price(); ok {
		_spec.SetField(price.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.AddedPrice(); ok {
		_spec.AddField(price.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.RecordedAt(); ok {
		_spec.SetField(price.FieldRecordedAt, field.TypeTime, value)
	}
	if pu.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   price.ProductTable,
			Columns: []string{price.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   price.ProductTable,
			Columns: []string{price.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.StoreCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   price.StoreTable,
			Columns: []string{price.StoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.StoreIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   price.StoreTable,
			Columns: []string{price.StoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{price.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PriceUpdateOne is the builder for updating a single Price entity.
type PriceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PriceMutation
}

// SetProductID sets the "product_id" field.
func (puo *PriceUpdateOne) SetProductID(i int) *PriceUpdateOne {
	puo.mutation.SetProductID(i)
	return puo
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (puo *PriceUpdateOne) SetNillableProductID(i *int) *PriceUpdateOne {
	if i != nil {
		puo.SetProductID(*i)
	}
	return puo
}

// SetStoreID sets the "store_id" field.
func (puo *PriceUpdateOne) SetStoreID(i int) *PriceUpdateOne {
	puo.mutation.SetStoreID(i)
	return puo
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (puo *PriceUpdateOne) SetNillableStoreID(i *int) *PriceUpdateOne {
	if i != nil {
		puo.SetStoreID(*i)
	}
	return puo
}

// SetPrice sets the "price" field.
func (puo *PriceUpdateOne) SetPrice(f float64) *PriceUpdateOne {
	puo.mutation.ResetPrice()
	puo.mutation.SetPrice(f)
	return puo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (puo *PriceUpdateOne) SetNillablePrice(f *float64) *PriceUpdateOne {
	if f != nil {
		puo.SetPrice(*f)
	}
	return puo
}

// AddPrice adds f to the "price" field.
func (puo *PriceUpdateOne) AddPrice(f float64) *PriceUpdateOne {
	puo.mutation.AddPrice(f)
	return puo
}

// SetRecordedAt sets the "recorded_at" field.
func (puo *PriceUpdateOne) SetRecordedAt(t time.Time) *PriceUpdateOne {
	puo.mutation.SetRecordedAt(t)
	return puo
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (puo *PriceUpdateOne) SetNillableRecordedAt(t *time.Time) *PriceUpdateOne {
	if t != nil {
		puo.SetRecordedAt(*t)
	}
	return puo
}

// SetProduct sets the "product" edge to the Product entity.
func (puo *PriceUpdateOne) SetProduct(p *Product) *PriceUpdateOne {
	return puo.SetProductID(p.ID)
}

// SetStore sets the "store" edge to the Store entity.
func (puo *PriceUpdateOne) SetStore(s *Store) *PriceUpdateOne {
	return puo.SetStoreID(s.ID)
}

// Mutation returns the PriceMutation object of the builder.
func (puo *PriceUpdateOne) Mutation() *PriceMutation {
	return puo.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (puo *PriceUpdateOne) ClearProduct() *PriceUpdateOne {
	puo.mutation.ClearProduct()
	return puo
}

// ClearStore clears the "store" edge to the Store entity.
func (puo *PriceUpdateOne) ClearStore() *PriceUpdateOne {
	puo.mutation.ClearStore()
	return puo
}

// Where appends a list predicates to the PriceUpdate builder.
func (puo *PriceUpdateOne) Where(ps ...predicate.Price) *PriceUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PriceUpdateOne) Select(field string, fields ...string) *PriceUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Price entity.
func (puo *PriceUpdateOne) Save(ctx context.Context) (*Price, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PriceUpdateOne) SaveX(ctx context.Context) *Price {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PriceUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PriceUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PriceUpdateOne) check() error {
	if puo.mutation.ProductCleared() && len(puo.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Price.product"`)
	}
	if puo.mutation.StoreCleared() && len(puo.mutation.StoreIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Price.store"`)
	}
	return nil
}

func (puo *PriceUpdateOne) sqlSave(ctx context.Context) (_node *Price, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(price.Table, price.Columns, sqlgraph.NewFieldSpec(price.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Price.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, price.FieldID)
		for _, f := range fields {
			if !price.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != price.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Price(); ok {
		_spec.SetField(price.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.AddedPrice(); ok {
		_spec.AddField(price.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.RecordedAt(); ok {
		_spec.SetField(price.FieldRecordedAt, field.TypeTime, value)
	}
	if puo.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   price.ProductTable,
			Columns: []string{price.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   price.ProductTable,
			Columns: []string{price.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.StoreCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   price.StoreTable,
			Columns: []string{price.StoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.StoreIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   price.StoreTable,
			Columns: []string{price.StoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Price{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{price.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
