// Code generated by ent, DO NOT EDIT.

package ent

import (
	"baseProject/ent/price"
	"baseProject/ent/product"
	"baseProject/ent/review"
	"baseProject/ent/store"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreCreate is the builder for creating a Store entity.
type StoreCreate struct {
	config
	mutation *StoreMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (sc *StoreCreate) SetName(s string) *StoreCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetLocation sets the "location" field.
func (sc *StoreCreate) SetLocation(s string) *StoreCreate {
	sc.mutation.SetLocation(s)
	return sc
}

// SetCity sets the "city" field.
func (sc *StoreCreate) SetCity(s string) *StoreCreate {
	sc.mutation.SetCity(s)
	return sc
}

// SetCountry sets the "country" field.
func (sc *StoreCreate) SetCountry(s string) *StoreCreate {
	sc.mutation.SetCountry(s)
	return sc
}

// SetZipcode sets the "zipcode" field.
func (sc *StoreCreate) SetZipcode(s string) *StoreCreate {
	sc.mutation.SetZipcode(s)
	return sc
}

// SetNillableZipcode sets the "zipcode" field if the given value is not nil.
func (sc *StoreCreate) SetNillableZipcode(s *string) *StoreCreate {
	if s != nil {
		sc.SetZipcode(*s)
	}
	return sc
}

// SetPhoto sets the "photo" field.
func (sc *StoreCreate) SetPhoto(s string) *StoreCreate {
	sc.mutation.SetPhoto(s)
	return sc
}

// SetNillablePhoto sets the "photo" field if the given value is not nil.
func (sc *StoreCreate) SetNillablePhoto(s *string) *StoreCreate {
	if s != nil {
		sc.SetPhoto(*s)
	}
	return sc
}

// SetLatitude sets the "latitude" field.
func (sc *StoreCreate) SetLatitude(f float64) *StoreCreate {
	sc.mutation.SetLatitude(f)
	return sc
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (sc *StoreCreate) SetNillableLatitude(f *float64) *StoreCreate {
	if f != nil {
		sc.SetLatitude(*f)
	}
	return sc
}

// SetLongitude sets the "longitude" field.
func (sc *StoreCreate) SetLongitude(f float64) *StoreCreate {
	sc.mutation.SetLongitude(f)
	return sc
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (sc *StoreCreate) SetNillableLongitude(f *float64) *StoreCreate {
	if f != nil {
		sc.SetLongitude(*f)
	}
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *StoreCreate) SetCreatedAt(t time.Time) *StoreCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *StoreCreate) SetNillableCreatedAt(t *time.Time) *StoreCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *StoreCreate) SetID(i int) *StoreCreate {
	sc.mutation.SetID(i)
	return sc
}

// AddProductIDs adds the "products" edge to the Product entity by IDs.
func (sc *StoreCreate) AddProductIDs(ids ...int) *StoreCreate {
	sc.mutation.AddProductIDs(ids...)
	return sc
}

// AddProducts adds the "products" edges to the Product entity.
func (sc *StoreCreate) AddProducts(p ...*Product) *StoreCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return sc.AddProductIDs(ids...)
}

// AddPriceIDs adds the "prices" edge to the Price entity by IDs.
func (sc *StoreCreate) AddPriceIDs(ids ...int) *StoreCreate {
	sc.mutation.AddPriceIDs(ids...)
	return sc
}

// AddPrices adds the "prices" edges to the Price entity.
func (sc *StoreCreate) AddPrices(p ...*Price) *StoreCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return sc.AddPriceIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (sc *StoreCreate) AddReviewIDs(ids ...int) *StoreCreate {
	sc.mutation.AddReviewIDs(ids...)
	return sc
}

// AddReviews adds the "reviews" edges to the Review entity.
func (sc *StoreCreate) AddReviews(r ...*Review) *StoreCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sc.AddReviewIDs(ids...)
}

// Mutation returns the StoreMutation object of the builder.
func (sc *StoreCreate) Mutation() *StoreMutation {
	return sc.mutation
}

// Save creates the Store in the database.
func (sc *StoreCreate) Save(ctx context.Context) (*Store, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StoreCreate) SaveX(ctx context.Context) *Store {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *StoreCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *StoreCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *StoreCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := store.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *StoreCreate) check() error {
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Store.name"`)}
	}
	if v, ok := sc.mutation.Name(); ok {
		if err := store.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Store.name": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "Store.location"`)}
	}
	if v, ok := sc.mutation.Location(); ok {
		if err := store.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "Store.location": %w`, err)}
		}
	}
	if _, ok := sc.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "Store.city"`)}
	}
	if v, ok := sc.mutation.City(); ok {
		if err := store.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Store.city": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "Store.country"`)}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Store.created_at"`)}
	}
	return nil
}

func (sc *StoreCreate) sqlSave(ctx context.Context) (*Store, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *StoreCreate) createSpec() (*Store, *sqlgraph.CreateSpec) {
	var (
		_node = &Store{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(store.Table, sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(store.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.Location(); ok {
		_spec.SetField(store.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := sc.mutation.City(); ok {
		_spec.SetField(store.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := sc.mutation.Country(); ok {
		_spec.SetField(store.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := sc.mutation.Zipcode(); ok {
		_spec.SetField(store.FieldZipcode, field.TypeString, value)
		_node.Zipcode = value
	}
	if value, ok := sc.mutation.Photo(); ok {
		_spec.SetField(store.FieldPhoto, field.TypeString, value)
		_node.Photo = value
	}
	if value, ok := sc.mutation.Latitude(); ok {
		_spec.SetField(store.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = value
	}
	if value, ok := sc.mutation.Longitude(); ok {
		_spec.SetField(store.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(store.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := sc.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.ProductsTable,
			Columns: []string{store.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.PricesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.PricesTable,
			Columns: []string{store.PricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(price.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.ReviewsTable,
			Columns: []string{store.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StoreCreateBulk is the builder for creating many Store entities in bulk.
type StoreCreateBulk struct {
	config
	err      error
	builders []*StoreCreate
}

// Save creates the Store entities in the database.
func (scb *StoreCreateBulk) Save(ctx context.Context) ([]*Store, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Store, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StoreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *StoreCreateBulk) SaveX(ctx context.Context) []*Store {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *StoreCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *StoreCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
