// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Price is the predicate function for price builders.
type Price func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// Store is the predicate function for store builders.
type Store func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
